<div id="<?php echo $this->escapeHtmlAttr($this->news_wrapper) ?>" class="relative-wrapper">
    <?php echo $this->data ?>
</div>
<?php if((!empty($this->base_filters['category']) || !empty($this->base_filters['date']))): ?>
    <?php $this->newsListUrl = $this->pageUrl('news-list') ?>
    <?php if(false !== $this->newsListUrl): ?>
        <hr />
        <p>
            <a href="<?php echo $this->url('page', ['page_name' => $this->newsListUrl], ['force_canonical' => true]) ?>">
                <?php echo $this->translate('View all news') ?>
            </a>
        </p>
    <?php endif ?>
<?php endif ?>