<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Add a news') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of news')) ?>

<!-- render a header -->
<?php echo $this->render('news/news-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is the "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of news'),
            'controller' => 'news-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'add_news' => [
            'name' => $this->subPageTitle,
            'controller' => 'news-administration',
            'action' => 'add-news',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('New news'),
    'body' => $this->partial('partial/form', ['form' => $this->news_form])
]) ?>