<?php use News\Model\NewsBase as NewsBaseModel ?>

<?php $this->declareVars('extraActions', 'subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Edit the news') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of news')) ?>

<!-- render a header -->
<?php echo $this->render('news/news-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is the "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of news'),
            'controller' => 'news-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'edit_news' => [
            'name' => $this->subPageTitle,
            'controller' => 'news-administration',
            'action' => 'edit-news',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'news-administration',
        'action' => 'delete-news',
        'name' => $this->translate('Delete the news'),
        'check_acl' => true,
        'confirm' => $this->translate('News will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'news' : [{$this->news['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'news-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => NewsBaseModel::STATUS_APPROVED == $this->news['status'],
        'controller' => 'news-administration',
        'action' => 'approve-news',
        'name' => $this->translate('Approve the news'),
        'check_acl' => true,
        'confirm' => $this->translate('News will be approved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'news' : [{$this->news['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'news-administration', 'action' => 'edit-news', 'slug' => $this->news['id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => NewsBaseModel::STATUS_APPROVED != $this->news['status'],
        'controller' => 'news-administration',
        'action' => 'disapprove-news',
        'name' => $this->translate('Disapprove the news'),
        'check_acl' => true,
        'confirm' => $this->translate('News will be disapproved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'news' : [{$this->news['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'news-administration', 'action' => 'edit-news', 'slug' => $this->news['id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'news-administration',
        'action' => 'add-news',
        'name' => $this->translate('Add a news'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', ['form' => $this->news_form])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', ['form' => $this->news_form])
            ]) ?>
        </div>
    <?php endif ?>
</div>