<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of news') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('news/news-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>


<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'news-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'headers' => [
        0 => [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        1 => [
            'title' => $this->translate('Title'),
            'order_name' => 'title'
        ],
        2 => [
            'title' => $this->translate('Status'),
            'order_name' => 'status'
        ],
        3 => [
            'title' => $this->translate('Date'),
            'order_name' => 'created'
        ]
    ],
    'paginator' => $this->paginator,
    'helpers' => [
        'status' => 'translate',
        'created' => 'applicationDate'
    ],
    'helpers_options' => [
        'created' => [
            'format' => $this->applicationSetting('news_date_format')
        ]
    ],
    'actions' => [
        'regular_actions' => [
            0 => [
                'name' => $this->translate('Add a news'),
                'controller' => 'news-administration',
                'action' => 'add-news',
                'check_acl' => true
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'news-list',
        'multiple_actions' => [
            'items_name' => 'news[]'
        ]
    ],
    'actions_extra_check' => [
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('News'),
    'body' => $this->content
]) ?>