<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('Settings') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('news/news-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'settings' // selected action is the "settings"
]) ?>