<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'News\Module'                                  => __DIR__ . '/Module.php',
    'News\Controller\NewsAdministrationController' => __DIR__ . '/src/News/Controller/NewsAdministrationController.php',
    'News\Event\NewsEvent'                         => __DIR__ . '/src/News/Event/NewsEvent.php',
    'News\Exception\NewsException'                 => __DIR__ . '/src/News/Exception/NewsException.php',
    'News\Form\News'                               => __DIR__ . '/src/News/Form/News.php',
    'News\Form\NewsCategory'                       => __DIR__ . '/src/News/Form/NewsCategory.php',
    'News\Form\NewsFilter'                         => __DIR__ . '/src/News/Form/NewsFilter.php',
    'News\Model\NewsAdministration'                => __DIR__ . '/src/News/Model/NewsAdministration.php',
    'News\Model\NewsBase'                          => __DIR__ . '/src/News/Model/NewsBase.php',
    'News\Model\NewsWidget'                        => __DIR__ . '/src/News/Model/NewsWidget.php',
    'News\PagePrivacy\NewsListPrivacy'             => __DIR__ . '/src/News/PagePrivacy/NewsListPrivacy.php',
    'News\PagePrivacy\NewsViewPrivacy'             => __DIR__ . '/src/News/PagePrivacy/NewsViewPrivacy.php',
    'News\PageProvider\NewsPageProvider'           => __DIR__ . '/src/News/PageProvider/NewsPageProvider.php',
    'News\Service\News'                            => __DIR__ . '/src/News/Service/News.php',
    'News\View\Helper\NewsImageUrl'                => __DIR__ . '/src/News/View/Helper/NewsImageUrl.php',
    'News\View\Widget\NewsAbstractWidget'          => __DIR__ . '/src/News/View/Widget/NewsAbstractWidget.php',
    'News\View\Widget\NewsCalendarWidget'          => __DIR__ . '/src/News/View/Widget/NewsCalendarWidget.php',
    'News\View\Widget\NewsCategoriesWidget'        => __DIR__ . '/src/News/View/Widget/NewsCategoriesWidget.php',
    'News\View\Widget\NewsLastNewsWidget'          => __DIR__ . '/src/News/View/Widget/NewsLastNewsWidget.php',
    'News\View\Widget\NewsListWidget'              => __DIR__ . '/src/News/View/Widget/NewsListWidget.php',
    'News\View\Widget\NewsSimilarNewsWidget'       => __DIR__ . '/src/News/View/Widget/NewsSimilarNewsWidget.php',
    'News\View\Widget\NewsViewWidget'              => __DIR__ . '/src/News/View/Widget/NewsViewWidget.php',
    'News\Test\NewsBootstrap'                      => __DIR__ . '/test/Bootstrap.php'
];
